### ISSUE TITLE
Created Timestamp in Satus Bar

### ISSUE THREAD

**Issue by sOER-Frank** [Yustynn/obsidian-last-modified-timestamp-in-status-bar#2] opened 2023-05-12 07:22 UTC
Dear Yustynn,

I am surprised that your plugin loaded so little. For me it is often very important to see when a note was last changed. So I am very happy to be able to use your plugin. But for me it is even more important to see when a note was created. Is it much effort to show this information also in the status bar?

Best regards!

**Comment by Yustynn** [comment] 2023-05-12 07:58
Hey Frank.

Sure thing, will add that feature soon.

Closing since this is a duplicate of #1

**Closed as completed by Yustynn** 2023-05-12 07:58 UTC
